---
- name: Configure service1
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
#  notify:
#    - Reload systemd

# - name: Enable ScyllaDB Server service
#   systemd:
#     name: scylla-server
#     enabled: yes

# - name: Start ScyllaDB Service
#   systemd:
#      name: scylla-server
#      state: started

