---
- name: Gather IP Address
  setup:
  register: target_host_info

- name: Configure service1
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  # notify:
  #   - Reload systemd

# For example: "<IP1>,<IP2>,<IP3>"
# - name: Configure ScyllaDB seeds
#   lineinfile:
#     path: /etc/scylla/scylla.yaml 
#     regexp: '^seeds:'
#     line: "seeds: {% for host in groups['tag_Name_one'] %}{{ hostvars[host].ansible_host }},{% endfor %} {% for host in groups['tag_Name_two'] %}{{ hostvars[host].ansible_host }},{% endfor %} {% for host in groups['tag_Name_three'] %}{{ hostvars[host].ansible_host }}{% endfor %}"


- name: Check Scylla Server service status
  systemd:
    name: scylla-server
    state: started

- name: Wait for a condition with a 2-minute timeout
  wait_for:
    timeout: 120

- name: Create user in Scylla
  command: >
    cqlsh -u cassandra -p cassandra '{{ target_host_info.ansible_facts.ansible_default_ipv4.address }}' -e
    "CREATE USER '{{ username }}' WITH PASSWORD '{{ passwd }}' SUPERUSER;"
  changed_when: false

- name: Create key in Scylla
  command: >
    cqlsh -u cassandra -p cassandra '{{ target_host_info.ansible_facts.ansible_default_ipv4.address }}' -e
    "CREATE KEYSPACE {{ keyname }} WITH replication = {'class':'SimpleStrategy', 'replication_factor':3};"
  changed_when: false
...
