---
- name: Configure service1
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  notify:
    - Reload systemd

- name: Create Scylla Users
  cqlsh:
    login_host: localhost
    login_user: admin_username
    login_password: admin_password
    statement: "CREATE ROLE 'new_user' WITH PASSWORD = 'password' AND LOGIN = true"
