---
- name: Configure service1
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
  notify:
    - Reload systemd
# - name: Create user in scylla
#   command: cqlsh -u cassandra -p cassandra  -e "CREATE USER '{{ username }}' WITH PASSWORD '{{ passwd }}' SUPERUSER;"
  # changed_when: false
# when: "user_exists.rc != 0"
# - name: Create Scylla Users
#   community.cassandra.cqlsh:
#     login_host: localhost
#     login_user:  cassandra
#     login_password:  cassandra
#     statement: "CREATE ROLE 'new_user' WITH PASSWORD = 'password' AND LOGIN = true"
