---
- name: Configure service1
  template:
    src: scylla.yaml.j2
    dest: /etc/scylla/scylla.yaml  #/etc/elasticsearch/elasticsearch.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: true
#  notify:
#    - Reload systemd

- name: Enable ScyllaDB Server service
  systemd:
    name: scylla-server
    enabled: yes

- name: Start ScyllaDB Service
  systemd:
     name: scylla-server
     state: started
    
#  remote_src: true
#    mode: '0644'
#  with_items: "{{ templl }}"

  # notify: Restart Elasticsearch

# - name: Configure scylla cassandra
#   template:
#     src: "{{ item }}"
#     dest: /etc/scylla/cassandra
#     owner: root
#     group: root
#     mode: '0644'
#   with_items: "{{ templs }}"
#   notify: Restart scylla

#/home/ubuntu/roletool1/roletool/templates/





# - name: Give insecure permissions to an existing file
#   ansible.builtin.file:
#     path: "{{ item }}"        #/etc/elasticsearch/elasticsearch.yml 
#     owner: root
# #     group: root
# #     mode: '0777'
# #   with_items: "{{ paths }}"
