---
- name: Update apt cache
  apt:
    update_cache: true

- name: Import ScyllaDB GPG Key
  command: "{{ s_gpg }}"
  changed_when: false

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"

- name: Update apt cache
  apt:
    update_cache: true

- name: Install scylla
  apt:
    name: scylla
    state: present
  # failed_when: false

- name: Run scylla
  command: scylla_setup
  args:
    stdin: "YES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes"
  register: scylla_setup_output
  changed_when: false
...
