---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install scylla
  apt:
    name: scylla
    state: present

- name: Run scylla_setup script
  command: sudo scylla_setup
  args:
    stdin: "\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\n"  # Provide your answers here
  register: scylla_setup_output
  become: yes
- debug:
    var: scylla_setup_output.stdout_lines
# - name: Enable ScyllaDB Server service
#   systemd:
#     name: scylla-server
#     enabled: yes

# - name: Start ScyllaDB Service
#   systemd:
#      name: scylla-server
#      state: started
