---
- name: Update apt cache
  apt:
    update_cache: yes
- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes
  changed_when: false

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes

# - name: Update apt cache
#   apt:
#     update_cache: yes

- name: Install scylla
  apt:
    update_cache: yes
    name: scylla
    state: present

- name: Run scylla
  command: scylla_setup
  become: yes
  args:
    stdin: "YES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes"
  register: scylla_setup_output
  when: scylla_setup_output is not defined or scylla_setup_output.changed
- debug:
    var: scylla_setup_output.stdout_lines

- name: Enable ScyllaDB Server service
  systemd:
    name: scylla-server
    enabled: yes

- name: Start ScyllaDB Service
  systemd:
     name: scylla-server
     state: started
