---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install scylla
  apt:
    name: scylla
    state: present


- name: Run scylla_setup
  command: yes | sudo scylla_setup
- name: Run scylla_setup
  expect:
    command: sudo scylla_setup
    responses:
          - "Do you want to run check your kernel version?\n": "YES\n"
          - "Do you want to verify the ScyllaDB packages are installed?\n": "YES\n"
          - "Do you want the Scylla server service to automatically start when the Scylla node boots?\n": "YES\n"
          - "Do you want to enable Scylla to check if there is a newer version of Scylla available?\n": "YES\n"
          - "Do you want to setup Network Time Protocol(NTP) to auto-synchronize the current time on the node?\n": "YES\n"
          - "Do you want to setup RAID and XFS?\n": "YES\n"
          - "Are you sure you want to setup RAID and XFS?\n": "YES\n"
          - "Do you want to change RAID level to RAID5?\n": "yes\n"
          - "Enable XFS online discard?\n": "YES\n"
          - "Do you want to enable coredumps?\n": "YES\n"
          - "Do you want to setup a system-wide customized configuration for Scylla?\n": "YES\n"
          - "Do you want to enable Network Interface Card (NIC) and disk(s) optimization?\n": "yes\n"
          - "The clocksource is the physical device that Linux uses to take time measurements. In most cases Linux chooses the fastest available clocksource device...\n": "yes\n"
          - "Do you want IOTune to study your disks IO profile and adapt Scylla to it?\n": "YES\n"
          - "Do you want to set the CPU scaling governor to Performance level on boot?\n": "YES\n"
          - "Do you want to configure swapfile?\n": "YES\n"
          - "Do you want to enable fstrim service?\n": "yes\n"
          - "Will Scylla be the only service on this host?\n": "YES\n"
          - "Do you want to create swapfile on the root directory?\n": "YES\n"
          - "Do you want to auto configure swap size?\n": "YES\n"
          - "Do you want to configure rsyslog to send log to a remote repository?\n": "YES\n"
          - "Please input rsyslog remote server, use ip:port format.\n": "your_rsyslog_server_ip:your_rsyslog_server_port\n"


# - name: Runscylla_setupscript
#   shell: scylla_setup
#   register: scylla_setup_output
#   private: false
# - name: Print a message
#   debug:
#       msg: 'output {{ scylla_setup_output.stdout }}'

# - name: Run scylla_setup script
#   shell: scylla_setup
#   become: yes
#   args:
#     stdin: "YES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes"  # Provide your answers here
#   register: scylla_setup_output
#   ignore_errors: yes
# - name: Wait for system initialization
#   wait_for:
#     timeout: 60 
# - name: Run scylla
#   command: scylla_setup
#   become: yes
#   args:
#     stdin: "YES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\nYES"  # Provide your answers here
#   register: scylla_setup_output
# - debug:
#     var: scylla_setup_output.stdout_lines


# - name: Enable ScyllaDB Server service
#   systemd:
#     name: scylla-server
#     enabled: yes

# - name: Start ScyllaDB Service
#   systemd:
#      name: scylla-server
#      state: started
